targets:
  $default:
    builders:
      page_route_generator|page_route_annotation:
        enabled: true

builders:
  page_route_generator:
    target: ":page_route_generator"
    import: "package:page_route_generator/page_route.generator.dart"
    builder_factories: ["generateRouteParam"]
    build_extensions: { ".dart": [".route_param_generator.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
