// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';

import 'package:project/shared/decorators/imitable.decorator.dart' as prefix0;
import 'package:project/shared/models/user.model.dart' as prefix1;
// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Imitable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'User',
            r'.User',
            7,
            0,
            const prefix0.Imitable(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix1.User.fromJson},
            {},
            {
              r'': (bool b) => (id, name, email, gender, status, selected) =>
                  b ? prefix1.User(id, name, email, gender, status) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 0,
              r'toString': 1,
              r'noSuchMethod': 0,
              r'hashCode': 1,
              r'runtimeType': 1,
              r'toJson': 1,
              r'id': 1,
              r'id=': 0,
              r'name': 1,
              r'name=': 0,
              r'email': 1,
              r'email=': 0,
              r'gender': 1,
              r'gender=': 0,
              r'status': 1,
              r'status=': 0,
              r'selected': 1,
              r'selected=': 0,
              r'fromJson': 0
            })
      ],
      null,
      null,
      <Type>[prefix1.User],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'id': (dynamic instance) => instance.id,
        r'name': (dynamic instance) => instance.name,
        r'email': (dynamic instance) => instance.email,
        r'gender': (dynamic instance) => instance.gender,
        r'status': (dynamic instance) => instance.status,
        r'selected': (dynamic instance) => instance.selected
      },
      {
        r'id=': (dynamic instance, value) => instance.id = value,
        r'name=': (dynamic instance, value) => instance.name = value,
        r'email=': (dynamic instance, value) => instance.email = value,
        r'gender=': (dynamic instance, value) => instance.gender = value,
        r'status=': (dynamic instance, value) => instance.status = value,
        r'selected=': (dynamic instance, value) => instance.selected = value
      },
      null,
      [
        const [1, 0, null],
        const [0, 0, null],
        const [6, 0, null]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
