targets:
  $default:
    builders:
      json_paramable_generator|json_paramable_annotation:
        enabled: true

builders:
  json_paramable_generator:
    target: ":json_paramable_generator"
    import: "package:json_paramable_generator/json_paramable_generator.dart"
    builder_factories: ["generateJsonParam"]
    build_extensions: { ".dart": [".json_paramable.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
